### PR TITLE
New test suite for comparing PRS vs non-PRS collection creation & restart

### PR DESCRIPTION
**Pull request by chatman**
The test does the following:

- Create 1k non-PRS collections
- Restart 7 nodes
- Delete all 1k collections
- Restart 7 nodes
- Create 1k PRS collections
- Restart 7 nodes

### CODE REVIEW

**Comment by justinrsweeney** [comment]
Nice! Would we also be able to add in a third test to this that is non-PRS w/ state.json compression? I think for that to be impactful we might want to do some collections with a large number of cores as well. It'd be interesting to at least measure alongside these other configurations.

**Comment by chatman** [comment]
Yes, that makes sense! That will be very helpful. I'll work on introducing
a mechanism to change the startup params / solr.xml during a restart.

**Comment by chatman** [comment]
I just studied the compression functionality a bit more and I'm thinking it deserves a test suite of its own. In that suite, there should be larger collections and should compare "non-PRS non compressed" vs "non-PRS compressed". I think we should work on it in a separate PR. WDYT, @justinrsweeney ?

**Comment by justinrsweeney** [comment]
I agree that the state.json compression test would generally be more relevant for larger collections, so that works for me as a separate PR.

**Comment by chatman** [comment]
Here's the collection creation performance for PRS vs non-PRS:
Screenshot from 2023-02-21 19-15-35

Here's the restart performance for PRS (restart-3) vs non-PRS (restart-1), see second graph here:
image

**Comment by chatman** [comment]
Green line is for non-PRS restart (restart-1), reference: https://github.com/fullstorydev/solr-bench/blob/master/suites/prs-vs-nonprs.json#L53

Red line is post PRS restart (restart-3).

The restart-2 corresponds to a restart after deleting all collections, didn't include it in the screenshot.

So, restart with PRS seems faster than non-PRS as per this suite.

**Pull request merged**
