### PR TITLE
pre-download: do not download files that are already present

### PR DESCRIPTION
**Pull request by nginthfs**
This PR avoids downloading `pre-download` files that are already present in the `CONFIGFILE_DIR`.

### CODE REVIEW

**Comment by chatman** [comment]
I thought wget's -c option inside the download() method takes care of this.
Is it not the case or not working?

**Comment by nginthfs** [comment]
That's not working on my machine or on a GCP VM running debian. The script will always redownload the `pre-download` files.

**Comment by nginthfs** [comment]
Ah, it's not working since I'm only ever downloading things via `gsutil`. I'll look into if there's a similar flag for `gsutil`.

**Comment by nginthfs** [comment]
Added `-n` to `gsutil cp`, which accomplishes the same thing.

**Comment by chatman** [comment]
Sounds good!

**Review by patsonluk — APPROVED** [review]
LGTM many thanks @nginthfs and @chatman for the review!

**Pull request merged**
